#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

test -x /usr/bin/xvkbd && xrdb -nocpp -merge $HOME/.dotfiles/etc/xvkbd/xvkbd-layout

#sxhkd &
#exec swm
#exec herbstluftwm

test -x /usr/bin/touchegg && touchegg >/dev/null &

export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
uim-xim &
export XMODIFIERS='@im=uim'

cd $HOME
exec pekwm
